# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoWiproPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage'
  pod 'MBProgressHUD'

  # Pods for DemoWiproPOC

  target 'DemoWiproPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoWiproPOCUITests' do
    # Pods for testing
  end

end




